Адаптивная сетка для страницы каталога
htmlacademy-adaptive/1593103-mishka-21 pull request #10
Opened 2020-12-07 02:43 UTC by bsgribtmfu

2020-12-07 20:38 UTC, Shramkoweb requested changes

2020-12-07 20:38 UTC, Shramkoweb commented on source/less/blocks/production.less
> +.production__button-play {
Модификатор?

2020-12-07 20:38 UTC, Shramkoweb commented on source/catalog.html
> +            <a class="site-navigation__link" href="#">Каталог товаров</a>
Почему опять появилась href="#"?

2020-12-07 20:38 UTC, Shramkoweb commented on source/catalog.html
> +            <a class="site-navigation__link" href="#">Вязание на заказ</a>
Это форма

2020-12-07 20:38 UTC, Shramkoweb commented on source/catalog.html
> +          <a class="main-navigation__logo">
Почему пропал href="index.html ?

2020-12-07 23:36 UTC, bsgribtmfu commented on source/less/blocks/production.less
> +.production__button-play {
Не, эта кнопка не имеет ничего общего с остальными кнопками

2020-12-08 17:43 UTC, bsgribtmfu commented
@Shramkoweb

2020-12-08 20:02 UTC, Shramkoweb approved these changes

2020-12-08 20:02 UTC, merged