Доверстка страницы формы
htmlacademy-adaptive/1593103-mishka-21 pull request #12
Opened 2020-12-23 03:30 UTC by bsgribtmfu

2020-12-23 22:44 UTC, Shramkoweb requested changes

2020-12-23 22:44 UTC, Shramkoweb commented on source/form.html
> +            <legend class="form-group__legend form-group__legend--margin">ФИО</legend>
Модификатор margin плохо. Придумай что-то более по смыслу.

2020-12-23 22:44 UTC, Shramkoweb commented on source/form.html
> +              <div class="form-group__wrapper-input form-group__wrapper-input--position">
position - аналогично.

2020-12-23 22:44 UTC, Shramkoweb commented on source/form.html
> +
Отступ лишний

2020-12-23 22:44 UTC, Shramkoweb commented on source/less/blocks/form-group.less
> +.form-group__input + .form-group__text:hover {
Ховер в начало

2020-12-27 22:47 UTC, bsgribtmfu commented on source/form.html
> +            <legend class="form-group__legend form-group__legend--margin">ФИО</legend>
не могу ничего придумать, этот модификатор добавляет отступ и только.

2020-12-28 08:36 UTC, Shramkoweb commented on source/form.html
> +            <legend class="form-group__legend form-group__legend--margin">ФИО</legend>
Проблема не в том, что он дает только отступ - это ок. А в том, что у него имя странно.
form-group__legend--margin ----> form-group__legend--full-name

2020-12-28 08:36 UTC, Shramkoweb commented on source/form.html
> +            <legend class="form-group__legend form-group__legend--margin">ФИО</legend>
Хотя бы как-то так)

2020-12-28 08:38 UTC, Shramkoweb commented
![image](https://user-images.githubusercontent.com/42001531/103201497-b32b9800-48f8-11eb-9f5b-9d2f6eb6833e.png) - нет ховера на эти инпуты.
![image](https://user-images.githubusercontent.com/42001531/103201514-bb83d300-48f8-11eb-9c16-2b37a887e452.png)

2020-12-28 08:38 UTC, merged