Разметка страницы формы
htmlacademy-adaptive/1593103-mishka-21 pull request #3
Opened 2020-11-16 16:04 UTC by bsgribtmfu

2020-11-16 18:26 UTC, bsgribtmfu commented
Еще давно я по невнимательности создал index.html в ветке module2-task2, разметил form.html и перед тем как запушить удалил index.html командой git rm index.html, после чего git выдал ошибку и попросил сделать пулреквест (без команды git add) иначе другие команды я выполнять не смогу. Я сделал пулреквест и подписал его "delite old index.html from task2". Позже внес изменения в form.html и тоже сделал пулреквест но уже не имея в своей ветке файла index.html. Теперь гитхаб пишет что обнаружен конфликт в файле index.html, но файла то нет, я его удалил, да и в гит я его не добавлял раньше от слова СОВСЕМ, я использовал всегда команду git add filename

2020-11-16 20:48 UTC, Shramkoweb requested changes

2020-11-16 20:48 UTC, Shramkoweb commented on source/form.html
> +          <li class="main-nav__item"><a href="#">Каталог товаров</a></li>
ссылка на каталог

2020-11-16 20:48 UTC, Shramkoweb commented on source/form.html
> +      <a class="page-header__logo">
ссылка на главную

2020-11-16 20:48 UTC, Shramkoweb commented on source/form.html
> +      <p class="order__full-title">
Это точно не заголовок. Это какоето вовлечение юзера

2020-11-16 20:48 UTC, Shramkoweb commented on source/form.html
> +          <legend>цвет</legend>
form__legend

2020-11-16 20:48 UTC, Shramkoweb commented on source/form.html
> +          <input class="form-group__input" type="checkbox" id="white" name="pink" value="pink">
name="pink" id="white"  ???)

2020-11-16 20:48 UTC, Shramkoweb commented on source/form.html
> +          <input class="form-group__radio" type="radio" id="white" name="type" value="true" checked>
id="white" ?

2020-11-16 20:48 UTC, Shramkoweb commented on source/form.html
> +          <input class="form-group__radio" type="radio" id="white" name="type" value="false">
id="white" ?

2020-11-16 20:48 UTC, Shramkoweb commented on source/form.html
> +          <label class="form-group__label" for="white">Аксессуар для интерьера</label>
C формой беда, перепроверь, что она работает корректно и в валидаторе.

2020-11-16 20:48 UTC, Shramkoweb commented on source/form.html
> +          <input class="form-group__radio" type="radio" id="white" name="type" value="false">
value="false" ??

2020-11-16 20:48 UTC, Shramkoweb commented on source/form.html
> +          <textarea class="form-group__text" type="text" name="meta" placeholder="Опишите все ваши пожелания к заказу"></textarea>
name="meta" ?? Почему мета?

2020-11-16 21:57 UTC, bsgribtmfu commented on source/form.html
> +          <legend>цвет</legend>
form-group__legend

2020-11-16 22:00 UTC, bsgribtmfu commented on source/form.html
> +      <p class="order__full-title">
как по мне так это самый настоящий заголовок, могу его обернуть в спан и закинуть в блок section, но тут встает вопрос, как его назвать, и когда начинаешь придумывать название в голову приходит только __title, потому что ниже есть __full-title, и по контенту и по расположению так и хочется оставить его заголовком хотя бы второго уровня.

2020-11-17 11:58 UTC, Shramkoweb commented on source/form.html
> +      <p class="order__full-title">
Ну всымысле? Title он обобщает суть блока идущего дальше? Тут просто слоган

Тебе хочется назвать его title -  просто потому как он идет первый. Это не аргмент))

2020-11-17 19:00 UTC, Shramkoweb approved these changes

2020-11-17 19:00 UTC, merged