Стилизация главной страницы
htmlacademy-adaptive/1593103-mishka-21 pull request #5
Opened 2020-11-19 17:15 UTC by bsgribtmfu

2020-11-19 18:45 UTC, Shramkoweb requested changes

2020-11-19 18:45 UTC, Shramkoweb commented on source/index.html
> +        <h2 class="promo__title">Милые штуки<br>ручной<br>работы для дома</h2>
Шириной нельзя было сделать?

2020-11-19 18:45 UTC, Shramkoweb commented on source/index.html
> +              <span class="promo-list__text">Предметы<br>интерьера</span>
Тут точно убирай

2020-11-19 18:45 UTC, Shramkoweb commented on source/index.html
> +              <span class="promo-list__text">Детские<br>игрушки</span>
Аналогично

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/about-us.less
> +  &::before {
Пустая строка перед новыми селекторами

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/about-us.less
> +  &::before {
```
.foo {

  .bar { }

}

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/button.less
> +@light-green: #63D1BB;
Переменные в отдельный файлик

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/contacs.less
> +    }
Отступ

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/button.less
> +    }
Отступ

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/contacs.less
> +    }
Отступ

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/fonts.less
> +  }
В конце файлов пустая строка - проверь, что у тебя она стоит?

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/footer.less
> +.page-footer {
Имя файла должно быть аналогично имени бем блока

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/main-navigation.less
> +
Личший отступ

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/main-navigation.less
> +    }
Отступы

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/navigation.less
> +  padding: 0;
Вынеси это в миксин и сбрасывай им списки

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/navigation.less
> +  box-sizing: border-box;
Бокс сайзинг поставь глобально - как мы делали на 1м курсе

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/navigation.less
> +.navigation a {
У `а` должен быть класс. Мы не используем тут теги

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/navigation.less
> +@black: #000000;
Зачем тут пременная?

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/page.less
> +@white: #FFFFFF;
А тут зачем переменная?

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/popular-product.less
> +@font-black: #000000;
Дублируешь переменные

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/popular-product.less
> +@font-black: #000000;
Для этого цвета уже гдето была перемпнная

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/popular-product.less
> +    & dd {
Классы - никаких тегов

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/popular-product.less
> +      float: left;
Точно флоат?)

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/popular-product.less
> +    & dt {
Отступ перед селектором

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/popular-product.less
> +  width: 100%;
Для картинок был пример чтобы они сохряняли пропорции и тянулись. Используй его

2020-11-19 18:45 UTC, Shramkoweb commented on source/less/popular-product.less
> +  width: 100%;
Глобально

2020-11-19 21:11 UTC, bsgribtmfu commented on source/less/about-us.less
> +  &::before {
даже во вложенных?

2020-11-19 23:46 UTC, bsgribtmfu commented on source/less/popular-product.less
> +      float: left;
пока что - да

2020-11-20 18:13 UTC, Shramkoweb reviewed
Проверь https://up.htmlacademy.ru/adaptive/21/criteries#b13

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/about-us.less
> +  &::before {
ДА

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/about-us.less
> +  &::before {
Почему нет?

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/contacs.less
> +  &-termin {
Это что?? Модификатор?

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/global.less
> +}
`img {
  display: block;
  max-width: 100%;
  height: auto;
}`

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/list-reset.less
> +.list-reset() {
Это в целом будет файл mixins.less
В котором могут быть все миксины

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/modal.less
> +  border: 1px solid #c6c6c6;
В переменную?

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/page-footer.less
> +  background-color: #f1f1f1;
В переменную?

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/popular-product.less
> +  &-termin {
??

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/popular-product.less
> +  &-details {
Это что за модификаторы?

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/promo-list.less
> +
Лишний отступ

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/reviews.less
> +
Лишний отступ

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/social.less
> +  border-bottom: 1px solid #e5e5e5;
В переменную

2020-11-20 18:13 UTC, Shramkoweb commented on source/less/user-navigation.less
>  .navigation {
Что делает блок navigation в файле user-navigation?

2020-11-20 18:14 UTC, Shramkoweb commented
+ у тебя упала проверка, проверь локально

2020-11-20 18:43 UTC, bsgribtmfu commented on source/less/contacs.less
> +  &-termin {
а такой подход только с модификатором возможен?

2020-11-20 18:45 UTC, bsgribtmfu commented on source/less/popular-product.less
> +  &-details {
это не модификаторы, это часть имени селектора

2020-11-20 22:05 UTC, Shramkoweb approved these changes

2020-11-20 22:05 UTC, merged