Стилизация страницы каталога №1
htmlacademy-adaptive/1593103-mishka-21 pull request #7
Opened 2020-11-24 22:35 UTC by bsgribtmfu

2020-11-25 07:58 UTC, Shramkoweb requested changes

2020-11-25 07:58 UTC, Shramkoweb commented on source/catalog.html
> +              <a class="navigation__link" href="#">Каталог товаров</a>
href="#" зачем добавил?

2020-11-25 07:58 UTC, Shramkoweb commented on source/catalog.html
> +            <img src="img/rabbit.png" class="product-card__image" alt="Вязанная игрушка - Зайчик попрыгайчик">
Проверь критерий по атрибутам высоты/ширины для картинок?

2020-11-25 07:58 UTC, Shramkoweb commented on source/less/blocks/order-form.less
> +.order-form__wrapper-input&:not(:last-child) {
`&:not(:last-child)` не нужен родительский `&` 
Просто `.order-form__wrapper-input:not(:last-child)`

2020-11-25 07:58 UTC, Shramkoweb commented on source/less/blocks/order-form.less
> +  border: 2px solid rgba(68, 68, 68, 0.1);
Цвета такого нет в переменных?

2020-11-25 07:58 UTC, Shramkoweb commented on source/less/blocks/production.less
> +    left: 1em;
прям em?

2020-11-26 00:35 UTC, bsgribtmfu commented on source/less/blocks/order-form.less
> +  border: 2px solid rgba(68, 68, 68, 0.1);
нужна прозрачность в рамке

2020-11-26 00:35 UTC, bsgribtmfu commented on source/less/blocks/order-form.less
> +.order-form__wrapper-input&:not(:last-child) {
опечаточка))

2020-11-26 00:36 UTC, bsgribtmfu commented on source/less/blocks/production.less
> +    left: 1em;
пока да, я вообще не вижу смысла позиционировать элемент до того как займусь адаптивной сеткой.

2020-11-26 18:59 UTC, Shramkoweb approved these changes

2020-11-26 18:59 UTC, merged