Адаптивная сетка для главной страницы
htmlacademy-adaptive/1593103-mishka-21 pull request #8
Opened 2020-11-30 22:26 UTC by bsgribtmfu

2020-12-01 20:07 UTC, Shramkoweb requested changes

2020-12-01 20:07 UTC, Shramkoweb commented on source/index.html
> +          <a class="site-navigation__link" href="#">Каталог товаров</a>
Ссылка на каталог =)

2020-12-01 20:07 UTC, Shramkoweb commented on source/index.html
> +            <svg class="user-navigation__image" width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
Ссылка на форму)

2020-12-01 20:07 UTC, Shramkoweb commented on source/index.html
> +          <blockquote style="display: none;" class="reviews__blockquote-item">
style="display: none;"  Что это и зачем?

2020-12-01 20:07 UTC, Shramkoweb commented on source/index.html
> +            <a class="contacs__link contacs__link--adress" href="#">г. Санкт-Петербург<br>ул. Большая Конюшенная<br>д. 19/8, офис 101</a>
А это точно ссылка - я вот подумал? Куда она будет вести?

2020-12-01 20:07 UTC, Shramkoweb commented on source/less/blocks/popular-product.less
> +    display: flex;
Он же уже `display: flex;` будет с `@tablet-width` зачем еще раз включать флекс на десктопе?

2020-12-01 20:07 UTC, Shramkoweb commented on source/less/blocks/popular-product.less
> +    display: flex;
https://yoksel.github.io/bad-practices/styles-in-mediaquery/

2020-12-01 20:07 UTC, Shramkoweb commented on source/less/blocks/popular-product.less
> +    position: relative;
Не дублируй код https://yoksel.github.io/bad-practices/styles-in-mediaquery/

2020-12-01 21:55 UTC, bsgribtmfu commented on source/index.html
> +          <blockquote style="display: none;" class="reviews__blockquote-item">
там две цитаты, а отображается одна.

2020-12-03 21:22 UTC, Shramkoweb requested changes

2020-12-03 21:22 UTC, Shramkoweb commented on source/index.html
> +          <blockquote class="reviews__blockquote-item reviews__blockquote-item--hidden">
👍

2020-12-03 21:22 UTC, Shramkoweb commented on source/less/blocks/button.less
> +  height: 52px;
При изменении контента может выпасть текст.
Лучше дать min-w

2020-12-03 21:22 UTC, Shramkoweb commented on source/less/blocks/contacs.less
>      width: 100%;
У тебя  width: 100%; уже будет с @tablet-width

2020-12-03 21:22 UTC, Shramkoweb commented on source/less/blocks/contacs.less
> +  .reset-indents();
Миксины обычно ставят в самом начале селектора

2020-12-03 21:22 UTC, Shramkoweb commented on source/less/blocks/promo.less
> +    margin: 0 auto;
Прям похоже на контейнер не?

2020-12-04 10:10 UTC, Shramkoweb approved these changes

2020-12-04 10:11 UTC, merged